### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by elszczepano** [elszczepano/mfr#1]
- [x] 1. Prepare an npm package. Release the package to the npm registry to book the name.
- [x] 2. Define detailed requirements. Rethink how the library should work and what set of features it should have.
- [x] 3. Prepare an MVP. This stage should deliver basic functionality.
- [x] 4. Add randomized file names approach.
- [x] 5. Add pattern filenames approach.
- [x] 6. Prepare a CLI version.
- [x] 7. Prepare README/documentation.
- [x] 8. Release the final version to the npm registry.

**Comment by elszczepano** [comment]
# Requirements

## The goal

The main goal of Mass File Renamer (MFR or mfr) is to quickly rename all files in provided directory. To make the tool more flexible the following options should be provided:
- mode:
    - random - the name should be a random string. There should be an option to provide prefixes and postfixes for each file.
    - pattern - the name is a pattern with mandatory postfix. Postfix can be a number or a random string.
- file formats - change files that match the provided format or array of formats.
- recursive - rename files in subdirectories.
- destination directory - the directory where all files should be copied.
- mutate - instead of rename and copying files, the original file names are mutated.

## How to use

The application should work in 2 modes:
- as a library - from the code level.
- as a CLI application.

**Comment by elszczepano** [comment]
CLI version issue https://github.com/elszczepano/mfr/issues/6
